//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchowcaseDisainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardStorage
    {
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string Description { get; set; }
        public byte[] DashboardBLOB { get; set; }
        public string DashboardXML { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public int StorageType { get; set; }
        public Nullable<int> DashboardOrder { get; set; }
        public byte[] DashboardPreview { get; set; }
    }
}
