#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishInstaller
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StaffIQTest")]
	public partial class DachboardDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDashboardStorage(DashboardStorage instance);
    partial void UpdateDashboardStorage(DashboardStorage instance);
    partial void DeleteDashboardStorage(DashboardStorage instance);
    #endregion
		
		public DachboardDataClassesDataContext() : 
				base(global::PublishInstaller.Properties.Settings.Default.StaffIQTestConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DachboardDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DachboardDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DachboardDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DachboardDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DashboardStorage> DashboardStorages
		{
			get
			{
				return this.GetTable<DashboardStorage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DashboardStorage")]
	public partial class DashboardStorage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Identifier;
		
		private string _Description;
		
		private System.Data.Linq.Binary _DashboardBLOB;
		
		private System.Xml.Linq.XElement _DashboardXML;
		
		private System.DateTime _PublicationDate;
		
		private int _StorageType;
		
		private System.Nullable<int> _DashboardOrder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentifierChanging(string value);
    partial void OnIdentifierChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDashboardBLOBChanging(System.Data.Linq.Binary value);
    partial void OnDashboardBLOBChanged();
    partial void OnDashboardXMLChanging(System.Xml.Linq.XElement value);
    partial void OnDashboardXMLChanged();
    partial void OnPublicationDateChanging(System.DateTime value);
    partial void OnPublicationDateChanged();
    partial void OnStorageTypeChanging(int value);
    partial void OnStorageTypeChanged();
    partial void OnDashboardOrderChanging(System.Nullable<int> value);
    partial void OnDashboardOrderChanged();
    #endregion
		
		public DashboardStorage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identifier", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Identifier
		{
			get
			{
				return this._Identifier;
			}
			set
			{
				if ((this._Identifier != value))
				{
					this.OnIdentifierChanging(value);
					this.SendPropertyChanging();
					this._Identifier = value;
					this.SendPropertyChanged("Identifier");
					this.OnIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DashboardBLOB", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DashboardBLOB
		{
			get
			{
				return this._DashboardBLOB;
			}
			set
			{
				if ((this._DashboardBLOB != value))
				{
					this.OnDashboardBLOBChanging(value);
					this.SendPropertyChanging();
					this._DashboardBLOB = value;
					this.SendPropertyChanged("DashboardBLOB");
					this.OnDashboardBLOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DashboardXML", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement DashboardXML
		{
			get
			{
				return this._DashboardXML;
			}
			set
			{
				if ((this._DashboardXML != value))
				{
					this.OnDashboardXMLChanging(value);
					this.SendPropertyChanging();
					this._DashboardXML = value;
					this.SendPropertyChanged("DashboardXML");
					this.OnDashboardXMLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicationDate", DbType="DateTime NOT NULL")]
		public System.DateTime PublicationDate
		{
			get
			{
				return this._PublicationDate;
			}
			set
			{
				if ((this._PublicationDate != value))
				{
					this.OnPublicationDateChanging(value);
					this.SendPropertyChanging();
					this._PublicationDate = value;
					this.SendPropertyChanged("PublicationDate");
					this.OnPublicationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StorageType", DbType="Int NOT NULL")]
		public int StorageType
		{
			get
			{
				return this._StorageType;
			}
			set
			{
				if ((this._StorageType != value))
				{
					this.OnStorageTypeChanging(value);
					this.SendPropertyChanging();
					this._StorageType = value;
					this.SendPropertyChanged("StorageType");
					this.OnStorageTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DashboardOrder", DbType="Int")]
		public System.Nullable<int> DashboardOrder
		{
			get
			{
				return this._DashboardOrder;
			}
			set
			{
				if ((this._DashboardOrder != value))
				{
					this.OnDashboardOrderChanging(value);
					this.SendPropertyChanging();
					this._DashboardOrder = value;
					this.SendPropertyChanged("DashboardOrder");
					this.OnDashboardOrderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
