//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowcaseETL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StaffIQTestEntities : DbContext
    {
        public StaffIQTestEntities()
            : base("name=StaffIQTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<StaffIQ> StaffIQ { get; set; }
        public virtual DbSet<Age> Age { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Floor> Floor { get; set; }
    }
}
